basedomain: simpleexpress.tk

image:
  repository: danielfsousa/simple-express
  tag: latest

resources:
  requests:
    cpu: '0.1'
    memory: 30M
  limits:
    cpu: '0.25'
    memory: 100M

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  averageCpuUtilization: 80
  averageMemoryUtilization: 80

livenessProbe:
  httpGet:
    path: /status/health
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /status/ready
    port: 3000
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 1

service:
  name: http
  type: NodePort
  externalPort: 3000
  internalPort: 3000

ingress:
  enabled: false

redis:
  usePassword: false
  cluster:
    enabled: false
    slaveCount: 1
  master:
    persistence:
      enabled: false

variables:
  NODE_ENV: development

secrets:
  SECRET: cGFzc3dvcmQ=
